### ISSUE TITLE
이미지 생성 화면 구현

### ISSUE THREAD

**Issue by josushell** [Nexters/ilab-android#12]
<img width="793" alt="스크린샷 2024-02-04 오전 10 34 23" src="https://github.com/Nexters/ilab-android/assets/63590121/b231638d-43fd-4e96-93b5-d95a6523c30f">

- [x] 이미지 생성 API 연동
- [x] 이미지 생성 완료 화면: 공유하기 버튼 bottom sheet
- [ ] 시간이 지연될때마다 주기적으로 텍스트 갱신

**Comment by easyhooon** [comment]
공유하기 -> 생성된 이미지 파일 자체를 전달하는 것(웹 url 공유 x)
