### ISSUE TITLE
Setting 화면 구현

### ISSUE THREAD

**Issue by josushell** [Nexters/ilab-android#28]
<img width="310" alt="스크린샷 2024-02-03 오후 9 16 36" src="https://github.com/Nexters/ilab-android/assets/63590121/5252d2e8-a4dc-4f4f-ad1b-492437219b59">

- [x] 개인정보처리방침 노션 웹뷰 연동
- [x] 계정 삭제 api
- [x] 현재 앱 버전 정보

**Comment by easyhooon** [comment]
@josushell Setting 화면 확인해봤는데 그 클릭 영역을 Icon 영역 말구 Cell 전체로 확장 해야할 것 같아

**Comment by josushell** [comment]
@easyhooon 오케이 그럼 cell에다가 클릭 걸도록 수정해서 다시 올릴게~!

**Comment by josushell** [comment]
@easyhooon 혹시 다크모드 앱 내에서 설정 가능하게 라디오 버튼 다시 살리는걸로 했었나? 피그마에는 안보여서~

**Comment by easyhooon** [comment]
@josushell 일단은 시스템 모드를 따라간다고 했던거 같네
