### ISSUE TITLE
홈 화면 UI

### ISSUE THREAD

**Issue by josushell** [Nexters/ilab-android#5]
<img width="179" alt="스크린샷 2024-02-04 오전 10 29 01" src="https://github.com/Nexters/ilab-android/assets/63590121/9e7c1968-4e77-43ce-88a1-f5118ca9f73c">
<img width="178" alt="스크린샷 2024-02-04 오전 10 29 50" src="https://github.com/Nexters/ilab-android/assets/63590121/4afb76e6-8761-4f19-a204-cce1152bd49a">

- [x] 홈 화면 UI

**Comment by easyhooon** [comment]
이 PR 이제 할거 다한거 같은데 merge 해도 될듯?
